##### Python stores the image as a Numpy array / matrix of numbers. 
colored image in - 3d matrix , if its grayscale image - 2D matrix.                                                         
color image has 3 channels - in (Red, Green, Blue) format.  And grayscale image has 1 channel - black & white.

In [1]:
import cv2

#### Read the image

In [2]:
img = cv2.imread("opencv.jpg", 1)  

# 1 : tells to keep in - colored image , its colored image it will convert into 3D matrix.
print(img)

[[[ 53  54  52]
  [ 53  54  52]
  [ 53  54  52]
  ...
  [ 22  22  22]
  [ 23  24  22]
  [ 23  24  22]]

 [[ 54  55  53]
  [ 54  55  53]
  [ 53  54  52]
  ...
  [ 22  22  22]
  [ 23  24  22]
  [ 23  24  22]]

 [[ 55  56  54]
  [ 54  55  53]
  [ 54  55  53]
  ...
  [ 22  22  22]
  [ 23  24  22]
  [ 23  24  22]]

 ...

 [[ 55  81 117]
  [ 56  82 118]
  [ 56  82 118]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 57  83 120]
  [ 57  83 120]
  [ 57  83 119]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 57  83 120]
  [ 58  84 121]
  [ 58  84 120]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


In [4]:
# 0 : gives grayscale image convert into 2D matrix
img = cv2.imread("opencv.jpg", 0)  
print(img)
print('\n shape : ', img.shape)   # (height, width) of image

[[53 53 53 ... 22 23 23]
 [54 54 53 ... 22 23 23]
 [55 54 54 ... 22 23 23]
 ...
 [89 90 90 ...  0  0  0]
 [91 91 91 ...  0  0  0]
 [91 92 92 ...  0  0  0]]

 shape :  (1600, 1074)


### Save image in OpenCV

In [5]:
cv2.imwrite('grayscale.jpg', img)    # save in any format jpg, png ('file name', image object)

True

#### Show the image

In [6]:
img = cv2.imread("opencv.jpg", 1)  

# imshow() : show image, 'legend' -image name given, img -var. stores image given above 
cv2.imshow("Legend", img)  

cv2.waitKey(0)           # waitKey(0) : shows image for 0 miliseconds when user presses any key
# cv2.waitkey(2000)      # if give some miliseconds like : 2000 it will go away after it automatically 

cv2.destroyAllWindows()    # when user presses any key it destroy all windows.

#### Resize the image

In [7]:
img = cv2.imread("opencv.jpg", 1)  

resized_img = cv2.resize(img, (600, 600))   # resize image - img, into (600,600) shape

cv2.imshow('legend', resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

##### Actually Its not symmetrical , we go ahead and divide by 2 / 3 the way we want it to resize. Also convert into 'int' bcoz it turns out to be in 'float'.

In [8]:
img = cv2.imread("opencv.jpg", 1)  

resized_img = cv2.resize(img, (int(img.shape[1]/2), int(img.shape[0]/2)))   # basically it makes half the shape of img.

cv2.imshow('legend', resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# we can also increase the size image , by multiplying with 2

resized_img = cv2.resize(img, (int(img.shape[1]*2), int(img.shape[0]*2)))   # basically it makes half the shape of img.

## Face Detection

###### Take a image - 

1.Create a 'cascade classifier' object, it will contain the features of the face (in xml file format). So that code determine where is the face.

2.use OpenCV - read the image and features of file and convert image into Numpy array (or convert color image into grayscale).  
3.detectMultiScale() : method to Search for the rows-columns values of the face numpy ndarray (face rectangle co-ordinates). scalefactor : decrease the shape value by 5%, until face is found. Smaller this value, greater is accuracy. 

4.Display the image with rectangular face box. (img, cordinates of img, RGB value of rectangle outline, width of rectangle).

##### In order to do object recognition/detection with cascade files, you first need cascade files. For the extremely popular tasks, these already exist. Detecting things like faces, cars, smiles, eyes, and license plates. Go to the folder where cv2 (or openc cv) installed, " opencv / data " here find '' haarcascade files ''.

In [9]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

img = cv2.imread("opencv.jpg", 1) 
# img = cv2.imread('grayscale.jpg', 1)

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray_img, scaleFactor=1.05, minNeighbors=5)

print(type(faces))
print(faces)

# (x,y) - starting coordinates, (x+w, y+h) - cordinates upto 'w' width and 'h' height, (0,255,0) -rgb color box, width of box 
for (x,y,w,h) in faces:
    img = cv2.rectangle(img, (x,y), (x+w, y+h), (0,255,0), 3)   
    
cv2.imshow('face detect', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[283 255 469 469]]


#### Face and eye detect

In [10]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("haarcascade_eye.xml")

img = cv2.imread("opencv.jpg", 1) 

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray_img, scaleFactor=1.05, minNeighbors=5)

for (x,y,w,h) in faces:
    cv2.rectangle(img, (x,y), (x+w, y+h), (0,255,0), 3)       # detect face
    
    roi_gray = gray_img[y:y+h, x:x+w]       # it helps to get the face only
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)   # and here detect eyes from 'roi_gray'
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,111),2)
        
cv2.imshow('face & eye detect', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## -----------------------------------

### How to use OpenCV to capture video with computer webcam

We will use OpenCV for reading frames/ images one-by-one. video is nothing but multiple images/multiple frames which 
are displayed very quickly, so that it looks like a video.
So we use loops to build a window where images appear really fast that you can see as a video.

1.create a ' VideoCapture(0) ' object, It will trigger the camera. '0' this number tell the computer to use built-in camera.
If want to use external camera then put here '1' and if using 2 cameras then put '2' inplcae of it.
If we have video file, then we can give path to that video file.

2.we need to import time module to use the camera for particular time (or to run the script).

3.release() : this will release the camera in miliseconds.

4.Now add a window that shows the video. 
" check " - Its boolean datatype, returns True, if python is able to read the VideoCapture Object.
" frame " - It numpy array, it represents the first image that video captures.

We need to create a frame object, which will read the images of the VideoCapture object.
We will recessively show each frame of the video being captured.
-> imshow() : to capture the 1st image / frame of the video.

In [1]:
import cv2, time

video = cv2.VideoCapture(0)

check, frame = video.read()
# print(check)  
# print(frame)

time.sleep(1)

cv2.imshow('Capture', frame)     # show the frames / image of the video

cv2.waitKey(0)

video.release()
cv2.destroyAllWindows()

<function destroyAllWindows>

#### till now we captured the 1st frame / image appeared in front of the camera

#### In order to capture the video, we will use ' while loop ' and condition is such that, unless ' check ' is True, Python will display the frames, if not able to read then condition will be ' False '.

In [1]:
import cv2, time

video = cv2.VideoCapture(0)

a = 1    # tells no. of frames, initially 1 

while True:
    a = a + 1       # here it will increase no .of frames by 1
    
    check, frame = video.read()
#     print(frame)
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)  # convert each frame into gray scale image
    cv2.imshow('Capture', gray)         # show image    
    
    key = cv2.waitKey(1)             # generate a new frame after every 1 miliseconds
    
    if key == ord('q'):
        break                  # once press the 'q' loop breaks, window will be destroyed
        

print(f'No. of frames captured : {a}')   # print number of frames
video.release()
cv2.destroyAllWindows()

No. of frames captured : 171


#### face and eye detect using webcam

In [2]:
import cv2

face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("haarcascade_eye.xml")

# creating fucntion for detection of face and eyes 
def detect(gray, frame):
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.05, minNeighbors=5)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0,255,0), 3)       # detect face
        
        roi_gray = gray[y:y+h, x:x+w]       # it helps to get the face only
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray, 1.1, 2)   # and here detect eyes from 'roi_gray'
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,111),2)
    return frame


# Using webcam to detect
video = cv2.VideoCapture(0)
while True:
    check, frame = video.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    detection = detect(gray, frame)
    cv2.imshow('face and eye detect webcam', detection)
    
    key = cv2.waitKey(1)
    if key == ord('q'):
        break

video.release()
cv2.destroyAllWindows()